version: '3.3'
services:
    tplink-energy-monitor:
        container_name: tplink-energy-monitor
        network_mode: host
        build:
          context: .
          dockerfile: Dockerfile
        volumes:
          - ./logs:/opt/tplink-monitor/logs
        restart: unless-stopped
        environment:
          - "PORT=$PORT"